using System.Diagnostics.CodeAnalysis;
using ValiCraft.Generator.Tests.Helpers;

namespace ValiCraft.Generator.Tests.StaticAsyncGeneratorTests;

public class SingleEnsureRuleChain_SingleRule_ThenStaticValidate_OnFailureModeHaltTest : IncrementalGeneratorTestBase<ValiCraftGenerator>
{
    [StringSyntax("CSharp")] private const string InputRequests = """
                                                             using System;
                                                             using System.Collections.Generic;

                                                             namespace Test.Requests;

                                                             public class Order
                                                             {
                                                                 public required string OrderNumber { get; set; }
                                                                 public decimal OrderTotal { get; set; }
                                                                 public required Customer Customer { get; set; }
                                                             }

                                                             public class Customer
                                                             {
                                                                 public required string Name { get; set; }
                                                             }
                                                             """;

    [StringSyntax("CSharp")] private const string InputCustomerValidator = """
                                                                        using Test.Requests;
                                                                        using ValiCraft;
                                                                        using ValiCraft.Attributes;
                                                                        using ValiCraft.BuilderTypes;

                                                                        namespace Test.Validators;

                                                                        [GenerateValidator]
                                                                        public partial class CustomerValidator : StaticValidator<Customer>
                                                                        {
                                                                            protected override void DefineRules(IValidationRuleBuilder<Customer> builder)
                                                                            {
                                                                                builder.Ensure(x => x.Name)
                                                                                   .IsNotNullOrWhiteSpace();
                                                                            }
                                                                        }
                                                                        """;

    [StringSyntax("CSharp")] private const string InputOrderValidator = """
                                                                        using Test.Requests;
                                                                        using ValiCraft;
                                                                        using ValiCraft.Attributes;
                                                                        using ValiCraft.AsyncBuilderTypes;

                                                                        namespace Test.Validators;

                                                                        [GenerateValidator]
                                                                        public partial class OrderValidator : StaticAsyncValidator<Order>
                                                                        {
                                                                            protected override void DefineRules(IAsyncValidationRuleBuilder<Order> orderBuilder)
                                                                            {
                                                                                orderBuilder.Ensure(x => x.Customer, OnFailureMode.Halt)
                                                                                   .IsNotNull()
                                                                                   .Validate<CustomerValidator>();
                                                                            }
                                                                        }
                                                                        """;

    [StringSyntax("CSharp")] private const string ExpectedCustomerValidator = """
                                                                        // <auto-generated />
                                                                        #nullable enable

                                                                        using Test.Requests;
                                                                        using ValiCraft;
                                                                        using ValiCraft.Attributes;
                                                                        using ValiCraft.BuilderTypes;

                                                                        namespace Test.Validators
                                                                        {
                                                                            /// <summary>
                                                                            /// Generated static validator for <see cref="global::Test.Requests.Customer"/>.
                                                                            /// </summary>
                                                                            public partial class CustomerValidator : global::ValiCraft.IStaticValidator<global::Test.Requests.Customer>
                                                                            {
                                                                                /// <inheritdoc />
                                                                                public static global::ValiCraft.ValidationErrors? Validate(global::Test.Requests.Customer request)
                                                                                {
                                                                                    var errors = RunValidationLogic(request, null);

                                                                                    if (errors is null) return null;

                                                                                    return new global::ValiCraft.ValidationErrors
                                                                                    {
                                                                                        Code = "CustomerErrors",
                                                                                        Message = "One or more validation errors occurred.",
                                                                                        Severity = global::ValiCraft.ErrorSeverity.Error,
                                                                                        Errors = errors
                                                                                    };
                                                                                }

                                                                                /// <inheritdoc />
                                                                                [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                                                                                public static global::System.Collections.Generic.List<global::ValiCraft.ValidationError>? RunValidation(global::Test.Requests.Customer request, string? inheritedTargetPath)
                                                                                {
                                                                                    return RunValidationLogic(request, inheritedTargetPath);
                                                                                }

                                                                                private static global::System.Collections.Generic.List<global::ValiCraft.ValidationError>? RunValidationLogic(global::Test.Requests.Customer request, string? inheritedTargetPath)
                                                                                {
                                                                                    global::System.Collections.Generic.List<global::ValiCraft.ValidationError>? errors = null;

                                                                                    if (!global::ValiCraft.Rules.NotNullOrWhiteSpace(request.Name))
                                                                                    {
                                                                                        errors ??= new(1);
                                                                                        errors.Add(new global::ValiCraft.ValidationError
                                                                                        {
                                                                                            Code = nameof(global::ValiCraft.Rules.NotNullOrWhiteSpace),
                                                                                            Message = $"Name must not be null or contain only whitespace.",
                                                                                            Severity = global::ValiCraft.ErrorSeverity.Error,
                                                                                            TargetName = "Name",
                                                                                            TargetPath = $"{inheritedTargetPath}Name",
                                                                                            AttemptedValue = request.Name,
                                                                                        });
                                                                                    }

                                                                                    return errors;
                                                                                }
                                                                            }
                                                                        }
                                                                        """;

    [StringSyntax("CSharp")] private const string ExpectedOrderValidator = """
                                                                        // <auto-generated />
                                                                        #nullable enable

                                                                        using Test.Requests;
                                                                        using ValiCraft;
                                                                        using ValiCraft.Attributes;
                                                                        using ValiCraft.AsyncBuilderTypes;

                                                                        namespace Test.Validators
                                                                        {
                                                                            /// <summary>
                                                                            /// Generated static async validator for <see cref="global::Test.Requests.Order"/>.
                                                                            /// </summary>
                                                                            public partial class OrderValidator : global::ValiCraft.IStaticAsyncValidator<global::Test.Requests.Order>
                                                                            {
                                                                                /// <inheritdoc />
                                                                                public static async global::System.Threading.Tasks.Task<global::ValiCraft.ValidationErrors?> ValidateAsync(global::Test.Requests.Order request, global::System.Threading.CancellationToken cancellationToken = default)
                                                                                {
                                                                                    var errors = await RunValidationLogicAsync(request, null, cancellationToken);

                                                                                    if (errors is null) return null;

                                                                                    return new global::ValiCraft.ValidationErrors
                                                                                    {
                                                                                        Code = "OrderErrors",
                                                                                        Message = "One or more validation errors occurred.",
                                                                                        Severity = global::ValiCraft.ErrorSeverity.Error,
                                                                                        Errors = errors
                                                                                    };
                                                                                }

                                                                                /// <inheritdoc />
                                                                                [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                                                                                public static async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<global::ValiCraft.ValidationError>?> RunValidationAsync(global::Test.Requests.Order request, string? inheritedTargetPath, global::System.Threading.CancellationToken cancellationToken)
                                                                                {
                                                                                    return await RunValidationLogicAsync(request, inheritedTargetPath, cancellationToken);
                                                                                }

                                                                                private static async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<global::ValiCraft.ValidationError>?> RunValidationLogicAsync(global::Test.Requests.Order request, string? inheritedTargetPath, global::System.Threading.CancellationToken cancellationToken)
                                                                                {
                                                                                    global::System.Collections.Generic.List<global::ValiCraft.ValidationError>? errors = null;

                                                                                    if (!global::ValiCraft.Rules.NotNull(request.Customer))
                                                                                    {
                                                                                        errors ??= new(2);
                                                                                        errors.Add(new global::ValiCraft.ValidationError
                                                                                        {
                                                                                            Code = nameof(global::ValiCraft.Rules.NotNull),
                                                                                            Message = $"Customer is required.",
                                                                                            Severity = global::ValiCraft.ErrorSeverity.Error,
                                                                                            TargetName = "Customer",
                                                                                            TargetPath = $"{inheritedTargetPath}Customer",
                                                                                            AttemptedValue = request.Customer,
                                                                                        });
                                                                                        goto HaltValidation_2;
                                                                                    }
                                                                                    var errors1 = global::Test.Validators.CustomerValidator.RunValidation(request.Customer, $"{inheritedTargetPath}Customer.");
                                                                                    if (errors1 is not null)
                                                                                    {
                                                                                        if (errors is null)
                                                                                        {
                                                                                            errors = errors1;
                                                                                            goto HaltValidation_2;
                                                                                        }
                                                                                        else
                                                                                        {
                                                                                            errors.AddRange(errors1);
                                                                                            goto HaltValidation_2;
                                                                                        }
                                                                                    }

                                                                                    HaltValidation_2:

                                                                                    return errors;
                                                                                }
                                                                            }
                                                                        }
                                                                        """;

    [Fact]
    public void ShouldGenerateStaticAsyncValidator()
    {
        AssertGenerator(inputs: [InputRequests, InputCustomerValidator, InputOrderValidator],
            outputs: [ExpectedCustomerValidator, ExpectedOrderValidator],
            diagnostics: [],
            assertInitialCompilation: true);
    }
}
