using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;
using ValiCraft.Generator.Shared;
using ValiCraft.Generator.Shared.Types;
using ValiCraft.Rules.Generator.Shared.Concepts;

namespace ValiCraft.Rules.Generator.Shared;

public static class ValidationRuleExtensionSourceProvider
{
    public static void EmitSourceCode(
        ImmutableArray<ProviderResult<ValidationRuleInfo>> validationRuleInfoResults,
        SourceProductionContext context)
    {
        foreach (var validationRuleInfoResult in validationRuleInfoResults)
        {
            if (validationRuleInfoResult.Diagnostics is { Count: > 0 })
            {
                foreach (var diagnostic in validationRuleInfoResult.Diagnostics)
                {
                    context.ReportDiagnostic(diagnostic);
                }

                continue;
            }
            
            var validationRule = validationRuleInfoResult.Value!;

            var sourceCode = $$"""
                               // <auto-generated />
                               #nullable enable

                               namespace {{validationRule.Class.Namespace}}
                               {
                                   {{validationRule.Class.Accessibility}} static class {{validationRule.Class.Name}}Extensions
                                   {
                                       [global::{{FullyQualifiedNames.Attributes.MapToValidationRule}}(
                                           validationRuleType: typeof({{validationRule.Class.FullyQualifiedUnboundedName}}),
                                           validationRuleGenericFormat: "{{validationRule.GetValidationRuleGenericFormat()}}")]
                                       {{validationRule.Class.Accessibility}} static global::{{FullyQualifiedNames.Interfaces.IValidationRuleBuilderType}}<TRequest, TPropertyType> {{validationRule.NameForExtensionMethod}}<{{validationRule.GetGenericArgumentsForExtensionMethod()}}>(
                                           {{GetMethodParameters(validationRule)}}) where TRequest : class
                                           => throw new global::System.NotImplementedException("Never gets called");
                                   }
                               }
                               """;

            context.AddSource($"{validationRule.Class.Name}.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
        }
    }

    private static string GetMethodParameters(ValidationRuleInfo validationRuleInfo)
    {
        return validationRuleInfo.GetParametersForExtensionMethod(
            $"this global::{FullyQualifiedNames.Interfaces.IBuilderType}<TRequest, TPropertyType> builder");
    }
}
