using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ValiCraft.Providers.LitePrimitives.Generator;

[Generator(LanguageNames.CSharp)]
public class ValidatorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var validatorInfoResult = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                FullyQualifiedNames.Attributes.GenerateValidator,
                predicate: ValidatorInfoProvider.Predicate,
                transform: ValidatorInfoProvider.Transform)
            .WithTrackingName(TrackingSteps.ValidatorInfoResultTrackingName);
        
        context.RegisterSourceOutput(
            validatorInfoResult.Collect(),
            static (spc, source) => Execute(source, spc));
    }

    private static void Execute(
        ImmutableArray<ValidatorInfoResult> validatorInfoResults,
        SourceProductionContext context)
    {
        foreach (var validatorInfoResult in validatorInfoResults)
        {
            if (validatorInfoResult.Diagnostics is { Count: > 0 })
            {
                foreach (var diagnostic in validatorInfoResult.Diagnostics)
                {
                    context.ReportDiagnostic(diagnostic);
                }

                continue;
            }
            
            var validatorInfo = validatorInfoResult.ValidatorInfo!;
            var sourceCode = $$"""
                             // <auto-generated />
                             #nullable enable
                             
                             namespace {{validatorInfo.NamespaceName}}
                             {
                                 public partial class {{validatorInfo.ClassName}} : {{FullyQualifiedNames.Interfaces.IValidator}}<{{validatorInfo.RequestTypeName}}>
                                 {
                                     public {{FullyQualifiedNames.Types.Validation}}<{{validatorInfo.RequestTypeName}}> Validate({{validatorInfo.RequestTypeName}} request)
                                     {
                                         return {{FullyQualifiedNames.Types.Validation}}<{{validatorInfo.RequestTypeName}}>.Success(request);
                                     }
                                 }
                             }
                             """;
            
            context.AddSource($"{validatorInfo.ClassName}.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
        }
    }
}