using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using ValiCraft.Generator.Shared;
using ValiCraft.Generator.Shared.Types;
using ValiCraft.Generator.Shared.Concepts;
using ValiCraft.Providers.LitePrimitives.Generator.Concepts;
using ValiCraft.Rules.Generator.Shared.Concepts;

namespace ValiCraft.Providers.LitePrimitives.Generator;

public static class ValidatorSourceProvider
{
    public static void EmitSourceCode(
        ImmutableArray<ProviderResult<ValidationRuleInfo>> validationRuleInfoResults,
        ImmutableArray<ProviderResult<ValidatorInfo>> validatorInfoResults,
        SourceProductionContext context)
    {
        var validRules = validationRuleInfoResults
            .Where(r => r.Value is not null)
            .Select(r => r.Value!)
            .ToList();

        foreach (var validatorInfoResult in validatorInfoResults)
        {
            if (validatorInfoResult.Diagnostics is { Count: > 0 })
            {
                foreach (var diagnostic in validatorInfoResult.Diagnostics)
                {
                    context.ReportDiagnostic(diagnostic);
                }
                continue;
            }
            
            var validatorInfo = validatorInfoResult.Value!;
            var validationRulesCode = new StringBuilder();
            
            BuildAllValidationRulesLogic(validationRulesCode, validatorInfo, validRules);

            var sourceCode = $$"""
                             // <auto-generated />
                             #nullable enable
                             
                             namespace {{validatorInfo.Class.Namespace}}
                             {
                                 {{validatorInfo.Class.Modifiers}} class {{validatorInfo.Class.Name}} : global::{{FullyQualifiedNames.Interfaces.IValidator}}<{{validatorInfo.RequestTypeName}}>
                                 {
                                     public global::{{FullyQualifiedNames.Types.Validation}}<{{validatorInfo.RequestTypeName}}> Validate({{validatorInfo.RequestTypeName}} request)
                                     {
                                         global::System.Collections.Generic.List<global::{{FullyQualifiedNames.Types.Error}}>? errors = null;
                                         
                             {{validationRulesCode}}
                                         return errors is not null
                                             ? global::{{FullyQualifiedNames.Types.Validation}}<{{validatorInfo.RequestTypeName}}>.Failure(errors)
                                             : global::{{FullyQualifiedNames.Types.Validation}}<{{validatorInfo.RequestTypeName}}>.Success(request);
                                     }
                                 }
                             }
                             """;

            context.AddSource($"{validatorInfo.Class.Name}.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
        }
    }

    private static void BuildAllValidationRulesLogic(
        StringBuilder validationRulesCode,
        ValidatorInfo validatorInfo,
        List<ValidationRuleInfo> validRules)
    {
        foreach (var ruleInvocation in validatorInfo.Rules) // Use the 'Rules' property as defined in your ValidatorInfo
        {
            var validationRuleGenericFormat = ruleInvocation.ValidationRuleGenericFormat;
            var fullyQualifiedValidationRule = ruleInvocation.FullyQualifiedValidationRule;
            
            if (string.IsNullOrEmpty(validationRuleGenericFormat) || string.IsNullOrEmpty(fullyQualifiedValidationRule))
            {
                var matchedRule = MapRuleInvocationToValidationRule(validRules, ruleInvocation);

                if (string.IsNullOrEmpty(validationRuleGenericFormat))
                {
                    validationRuleGenericFormat = matchedRule?.GetValidationRuleGenericFormat() ?? string.Empty;
                }

                if (string.IsNullOrEmpty(fullyQualifiedValidationRule))
                {
                    fullyQualifiedValidationRule = matchedRule?.Class.FullyQualifiedWithoutGenerics ?? string.Empty;
                }
            }
            
            var constructedValidationRuleGeneric = string.Empty;

            if (!string.IsNullOrEmpty(validationRuleGenericFormat))
            {
                constructedValidationRuleGeneric = ConstructValidationRuleGeneric(
                    validationRuleGenericFormat,
                    ruleInvocation);
            }
                
            var ifBlock = BuildValidationRuleLogic(
                validatorInfo,
                ruleInvocation,
                fullyQualifiedValidationRule,
                constructedValidationRuleGeneric);
            validationRulesCode.AppendLine(ifBlock);
        }
    }

    private static string ConstructValidationRuleGeneric(
        string validationRuleGenericFormat,
        RuleInvocation ruleInvocation)
    {
        // We add the property to the argument list as this is how the validation rule's IsValid method is formatted
        var argumentParameters = ruleInvocation.Arguments.Prepend(ruleInvocation.Property).ToArray();
        
        return string.Format(validationRuleGenericFormat, argumentParameters.Select(argument => argument.Type).ToArray());
    }

    private static ValidationRuleInfo? MapRuleInvocationToValidationRule(
        List<ValidationRuleInfo> validRules,
        RuleInvocation rule)
    {
        ValidationRuleInfo? bestMatchedRule = null;
        
        foreach (var validRule in validRules.Where(x => x.NameForExtensionMethod == rule.MethodName))
        {
            // We skip the first parameter as this will always be the property type
            var matchesResult = validRule.IsValidSignature.MatchesTypes(rule.Arguments, 1);
            
            // Check if we have a direct match with signature types
            // If so, we can return early
            if (matchesResult == SignatureMatching.Full)
            {
                return validRule;
            }

            if (matchesResult == SignatureMatching.Partial)
            {
                // We may want to do some rankings in the future
                // if we can determine if a parameter is non-generic and matches
                bestMatchedRule = validRule;
            }
        }
        
        return bestMatchedRule;
    }
    
    private static string BuildValidationRuleLogic(
        ValidatorInfo validatorInfo,
        RuleInvocation ruleInvocation,
        string fullyQualifiedValidationRule,
        string constructedRuleTypeInvocation)
    {
        var propertyAccessString = $"request.{ruleInvocation.Property.Name}";
    
        var isValidCallArgs = new List<string> { propertyAccessString };
        isValidCallArgs.AddRange(ruleInvocation.Arguments.GetArray()?.Select(x => x.Name) ?? Enumerable.Empty<string>());
        var isValidCallArgsString = string.Join(", ", isValidCallArgs);

        // To get the constructed type name like 'GenericRule<string, int, bool>',
        // we need to know the property type and the argument types.
        // The extension method's generic arguments hold this: <TRequest, TPropertyType, TParam1, TParam2...>
        // We can get them from the RuleInvocation.

        var validationRuleInvocation = $"global::{fullyQualifiedValidationRule}{constructedRuleTypeInvocation}";
        var errorTypeName = $"global::{FullyQualifiedNames.Types.Error}";
        var validationLogic = new StringBuilder();
        validationLogic.AppendLine($"            if (!{validationRuleInvocation}.IsValid({isValidCallArgsString}))");
        validationLogic.AppendLine("            {");
        validationLogic.AppendLine("                errors ??= new();");
        validationLogic.AppendLine($"                errors.Add({errorTypeName}.Validation(nameof({validationRuleInvocation}), \"An error has occurred\"));");
        validationLogic.Append("            }");
    
        return validationLogic.ToString();
    }
}