using System.Diagnostics.CodeAnalysis;
using ValiCraft.Generator.Tests.Helpers;

namespace ValiCraft.Generator.Tests.AsyncGeneratorTests;

public class SingleEnsureEachRuleChain_DirectRule_MultipleRules_WithOverridesTest : IncrementalGeneratorTestBase<ValiCraftGenerator>
{
    [StringSyntax("CSharp")] private const string InputRequests = """
                                                             using System.Collections.Generic;

                                                             namespace Test.Requests;

                                                             public class Request
                                                             {
                                                                 public required List<string> Tags { get; set; }
                                                             }
                                                             """;

    [StringSyntax("CSharp")] private const string InputValidatorsToGenerate = """
                                                                        using Test.Requests;
                                                                        using ValiCraft;
                                                                        using ValiCraft.Attributes;
                                                                        using ValiCraft.AsyncBuilderTypes;

                                                                        namespace Test.Validators;

                                                                        [GenerateValidator]
                                                                        public partial class RequestValidator : AsyncValidator<Request>
                                                                        {
                                                                            protected override void DefineRules(IAsyncValidationRuleBuilder<Request> builder)
                                                                            {
                                                                                builder.EnsureEach(p => p.Tags)
                                                                                    .IsNotNullOrWhiteSpace()
                                                                                        .WithMessage("{TargetName} must be provided")
                                                                                        .WithErrorCode("TAG_REQUIRED")
                                                                                        .WithTargetName("Tag")
                                                                                    .HasMinLength(3);
                                                                            }
                                                                        }
                                                                        """;

    [StringSyntax("CSharp")] private const string ExpectedValidators = """
                                                                       // <auto-generated />
                                                                       #nullable enable

                                                                       using Test.Requests;
                                                                       using ValiCraft;
                                                                       using ValiCraft.Attributes;
                                                                       using ValiCraft.AsyncBuilderTypes;

                                                                       namespace Test.Validators
                                                                       {
                                                                           /// <summary>
                                                                           /// Generated async validator for <see cref="global::Test.Requests.Request"/>.
                                                                           /// </summary>
                                                                           public partial class RequestValidator : global::ValiCraft.IAsyncValidator<global::Test.Requests.Request>
                                                                           {
                                                                               /// <inheritdoc />
                                                                               public async global::System.Threading.Tasks.Task<global::ValiCraft.ValidationErrors?> ValidateAsync(global::Test.Requests.Request request, global::System.Threading.CancellationToken cancellationToken = default)
                                                                               {
                                                                                   var errors = await RunValidationAsync(request, null, cancellationToken);

                                                                                   if (errors is null) return null;

                                                                                   return new global::ValiCraft.ValidationErrors
                                                                                   {
                                                                                       Code = "RequestErrors",
                                                                                       Message = "One or more validation errors occurred.",
                                                                                       Severity = global::ValiCraft.ErrorSeverity.Error,
                                                                                       Errors = errors
                                                                                   };
                                                                               }

                                                                               /// <summary>
                                                                               /// Runs the validation logic and returns the raw error list. This method is intended for internal use by nested validators.
                                                                               /// </summary>
                                                                               [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                                                                               public async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<global::ValiCraft.ValidationError>?> RunValidationAsync(global::Test.Requests.Request request, string? inheritedTargetPath, global::System.Threading.CancellationToken cancellationToken)
                                                                               {
                                                                                   global::System.Collections.Generic.List<global::ValiCraft.ValidationError>? errors = null;

                                                                                   var index2 = 0;
                                                                                   foreach (var element in request.Tags)
                                                                                   {
                                                                                       if (!global::ValiCraft.Rules.NotNullOrWhiteSpace(element))
                                                                                       {
                                                                                           errors ??= new(2);
                                                                                           errors.Add(new global::ValiCraft.ValidationError
                                                                                           {
                                                                                               Code = "TAG_REQUIRED",
                                                                                               Message = $"Tag must be provided",
                                                                                               Severity = global::ValiCraft.ErrorSeverity.Error,
                                                                                               TargetName = "Tag",
                                                                                               TargetPath = $"{inheritedTargetPath}{(inheritedTargetPath is not null ? "Tags[{index2}]" : null)}",
                                                                                               AttemptedValue = element,
                                                                                           });
                                                                                       }
                                                                                       if (!global::ValiCraft.Rules.MinLength(element, 3))
                                                                                       {
                                                                                           errors ??= new(1);
                                                                                           errors.Add(new global::ValiCraft.ValidationError
                                                                                           {
                                                                                               Code = nameof(global::ValiCraft.Rules.MinLength),
                                                                                               Message = $"Tags must have a minimum length of 3",
                                                                                               Severity = global::ValiCraft.ErrorSeverity.Error,
                                                                                               TargetName = "Tags",
                                                                                               TargetPath = $"{inheritedTargetPath}{(inheritedTargetPath is not null ? "Tags[{index2}]" : null)}",
                                                                                               AttemptedValue = element,
                                                                                           });
                                                                                       }
                                                                                       index2++;
                                                                                   }

                                                                                   return errors;
                                                                               }
                                                                           }
                                                                       }
                                                                       """;

    [Fact]
    public void ShouldGenerateValidator()
    {
        AssertGenerator(inputs: [InputRequests, InputValidatorsToGenerate],
            outputs: [ExpectedValidators],
            diagnostics: [],
            assertInitialCompilation: true);
    }
}
