using System.Diagnostics.CodeAnalysis;
using ValiCraft.Generator.Tests.Helpers;

namespace ValiCraft.Generator.Tests.AsyncGeneratorTests;

public class SingleEnsureRuleChain_MethodTarget_WithParametersTest : IncrementalGeneratorTestBase<ValiCraftGenerator>
{
    [StringSyntax("CSharp")] private const string InputRequests = """
                                                             using System;

                                                             namespace Test.Requests;

                                                             public class Product
                                                             {
                                                                 public decimal Price { get; set; }
                                                                 public int Quantity { get; set; }
                                                                 public decimal GetTotal(decimal taxRate) => Price * Quantity * (1 + taxRate);
                                                             }
                                                             """;

    // Define the validator against our request types.
    // This will generate a Validate method in a partial class.
    [StringSyntax("CSharp")] private const string InputValidatorsToGenerate = """
                                                                         using Test.Requests;
                                                                         using ValiCraft;
                                                                         using ValiCraft.Attributes;
                                                                         using ValiCraft.BuilderTypes;

                                                                         namespace Test.Validators;

                                                                         [GenerateValidator]
                                                                         public partial class ProductValidator : AsyncValidator<Product>
                                                                         {
                                                                             protected override void DefineRules(IAsyncValidationRuleBuilder<Product> productBuilder)
                                                                             {
                                                                                 productBuilder.Ensure(x => x.GetTotal(0.1m))
                                                                                     .IsGreaterThan(0);
                                                                             }
                                                                         }
                                                                         """;

    [StringSyntax("CSharp")] private const string ExpectedValidators = """
                                                                       // <auto-generated />
                                                                       #nullable enable

                                                                       using Test.Requests;
                                                                       using ValiCraft;
                                                                       using ValiCraft.Attributes;
                                                                       using ValiCraft.BuilderTypes;

                                                                       namespace Test.Validators
                                                                       {
                                                                           /// <summary>
                                                                           /// Generated async validator for <see cref="global::Test.Requests.Product"/>.
                                                                           /// </summary>
                                                                           public partial class ProductValidator : global::ValiCraft.IAsyncValidator<global::Test.Requests.Product>
                                                                           {
                                                                               /// <inheritdoc />
                                                                               public async global::System.Threading.Tasks.Task<global::ValiCraft.ValidationErrors?> ValidateAsync(global::Test.Requests.Product request, global::System.Threading.CancellationToken cancellationToken = default)
                                                                               {
                                                                                   var errors = await RunValidationAsync(request, null, cancellationToken);

                                                                                   if (errors is null) return null;

                                                                                   return new global::ValiCraft.ValidationErrors
                                                                                   {
                                                                                       Code = "ProductErrors",
                                                                                       Message = "One or more validation errors occurred.",
                                                                                       Severity = global::ValiCraft.ErrorSeverity.Error,
                                                                                       Errors = errors
                                                                                   };
                                                                               }

                                                                               /// <summary>
                                                                               /// Runs the validation logic and returns the raw error list. This method is intended for internal use by nested validators.
                                                                               /// </summary>
                                                                               [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                                                                               public async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<global::ValiCraft.ValidationError>?> RunValidationAsync(global::Test.Requests.Product request, string? inheritedTargetPath, global::System.Threading.CancellationToken cancellationToken)
                                                                               {
                                                                                   global::System.Collections.Generic.List<global::ValiCraft.ValidationError>? errors = null;

                                                                                   if (!global::ValiCraft.Rules.GreaterThan(request.GetTotal(0.1m), 0))
                                                                                   {
                                                                                       errors ??= new(1);
                                                                                       errors.Add(new global::ValiCraft.ValidationError
                                                                                       {
                                                                                           Code = nameof(global::ValiCraft.Rules.GreaterThan),
                                                                                           Message = $"Get Total must be greater than 0. Value received is {request.GetTotal(0.1m)}",
                                                                                           Severity = global::ValiCraft.ErrorSeverity.Error,
                                                                                           TargetName = "Get Total",
                                                                                           TargetPath = $"{inheritedTargetPath}GetTotal",
                                                                                           AttemptedValue = request.GetTotal(0.1m),
                                                                                       });
                                                                                   }

                                                                                   return errors;
                                                                               }
                                                                           }
                                                                       }
                                                                       """;

    [Fact]
    public void ShouldGenerateAsyncValidator()
    {
        AssertGenerator(inputs: [InputRequests, InputValidatorsToGenerate],
            outputs: [ExpectedValidators],
            diagnostics: [],
            assertInitialCompilation: true);
    }
}
