using System.Diagnostics.CodeAnalysis;
using ValiCraft.Generator.Tests.Helpers;

namespace ValiCraft.Generator.Tests.AsyncGeneratorTests;

public class SingleEnsureRuleChain_MethodTarget_WithOverridesTest : IncrementalGeneratorTestBase<ValiCraftGenerator>
{
    [StringSyntax("CSharp")] private const string InputRequests = """
                                                             using System;

                                                             namespace Test.Requests;

                                                             public class Account
                                                             {
                                                                 public decimal Balance { get; set; }
                                                                 public decimal GetAvailableBalance() => Balance;
                                                             }
                                                             """;

    // Define the validator against our request types.
    // This will generate a Validate method in a partial class.
    [StringSyntax("CSharp")] private const string InputValidatorsToGenerate = """
                                                                         using Test.Requests;
                                                                         using ValiCraft;
                                                                         using ValiCraft.Attributes;
                                                                         using ValiCraft.BuilderTypes;
                                                                         using ErrorCraft;

                                                                         namespace Test.Validators;

                                                                         [GenerateValidator]
                                                                         public partial class AccountValidator : AsyncValidator<Account>
                                                                         {
                                                                             protected override void DefineRules(IAsyncValidationRuleBuilder<Account> accountBuilder)
                                                                             {
                                                                                 accountBuilder.Ensure(x => x.GetAvailableBalance())
                                                                                     .IsGreaterThan(0)
                                                                                         .WithMessage("Insufficient funds")
                                                                                         .WithErrorCode("INSUFFICIENT_FUNDS");
                                                                             }
                                                                         }
                                                                         """;

    [StringSyntax("CSharp")] private const string ExpectedValidators = """
                                                                       // <auto-generated />
                                                                       #nullable enable

                                                                       using Test.Requests;
                                                                       using ValiCraft;
                                                                       using ValiCraft.Attributes;
                                                                       using ValiCraft.BuilderTypes;
                                                                       using ErrorCraft;

                                                                       namespace Test.Validators
                                                                       {
                                                                           /// <summary>
                                                                           /// Generated async validator for <see cref="global::Test.Requests.Account"/>.
                                                                           /// </summary>
                                                                           public partial class AccountValidator : global::ValiCraft.IAsyncValidator<global::Test.Requests.Account>
                                                                           {
                                                                               /// <inheritdoc />
                                                                               public async global::System.Threading.Tasks.Task<global::MonadCraft.Result<global::ErrorCraft.IValidationErrors, global::Test.Requests.Account>> ValidateAsync(global::Test.Requests.Account request, global::System.Threading.CancellationToken cancellationToken = default)
                                                                               {
                                                                                   var errors = await RunValidationLogicAsync(request, null, cancellationToken);

                                                                                   return errors is not null
                                                                                       ? global::MonadCraft.Result<global::ErrorCraft.IValidationErrors, global::Test.Requests.Account>.Failure(new global::ErrorCraft.ValidationErrors
                                                                                       {
                                                                                           Code = "AccountErrors",
                                                                                           Message = "One or more validation errors occurred.",
                                                                                           Severity = global::ErrorCraft.ErrorSeverity.Error,
                                                                                           Errors = errors
                                                                                       })
                                                                                       : global::MonadCraft.Result<global::ErrorCraft.IValidationErrors, global::Test.Requests.Account>.Success(request);
                                                                               }

                                                                               /// <inheritdoc />
                                                                               public async global::System.Threading.Tasks.Task<global::System.Collections.Generic.IReadOnlyList<global::ErrorCraft.IValidationError>> ValidateToListAsync(global::Test.Requests.Account request, global::System.Threading.CancellationToken cancellationToken = default)
                                                                               {
                                                                                   return await RunValidationLogicAsync(request, null, cancellationToken) ?? [];
                                                                               }

                                                                               /// <inheritdoc />
                                                                               [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                                                                               public async global::System.Threading.Tasks.Task<global::System.Collections.Generic.IReadOnlyList<global::ErrorCraft.IValidationError>> ValidateToListAsync(global::Test.Requests.Account request, string? inheritedTargetPath, global::System.Threading.CancellationToken cancellationToken = default)
                                                                               {
                                                                                   return await RunValidationLogicAsync(request, inheritedTargetPath, cancellationToken) ?? [];
                                                                               }

                                                                               private async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<global::ErrorCraft.IValidationError>?> RunValidationLogicAsync(global::Test.Requests.Account request, string? inheritedTargetPath, global::System.Threading.CancellationToken cancellationToken)
                                                                               {
                                                                                   global::System.Collections.Generic.List<global::ErrorCraft.IValidationError>? errors = null;

                                                                                   if (!global::ValiCraft.Rules.GreaterThan(request.GetAvailableBalance(), 0))
                                                                                   {
                                                                                       errors ??= new(1);
                                                                                       errors.Add(new global::ErrorCraft.ValidationError<decimal>
                                                                                       {
                                                                                           Code = "INSUFFICIENT_FUNDS",
                                                                                           Message = $"Insufficient funds",
                                                                                           Severity = global::ErrorCraft.ErrorSeverity.Error,
                                                                                           TargetName = "Get Available Balance",
                                                                                           TargetPath = $"{inheritedTargetPath}GetAvailableBalance",
                                                                                           AttemptedValue = request.GetAvailableBalance(),
                                                                                       });
                                                                                   }

                                                                                   return errors;
                                                                               }
                                                                           }
                                                                       }
                                                                       """;

    [Fact]
    public void ShouldGenerateAsyncValidator()
    {
        AssertGenerator(inputs: [InputRequests, InputValidatorsToGenerate],
            outputs: [ExpectedValidators],
            diagnostics: [],
            assertInitialCompilation: true);
    }
}
