using AwesomeAssertions.Execution;
using ValiCraft.Abstractions;
using ValiCraft.Generator.Shared;
using ValiCraft.TestHelpers;

namespace ValiCraft.Rules.Generator.Tests;

public class ValidationRuleExtensionGeneratorTests
{
    [Fact]
    public void ShouldGenerateValidationRuleExtensions()
    {
        const string input = """
                             using ValiCraft.Abstractions;
                             using ValiCraft.Abstractions.Attributes;
                             
                             namespace Test;
                             
                             [GenerateRuleExtension("IsNotNullOrEmpty")]
                             public class NotNullOrEmptyRule : IValidationRule<string?>
                             {
                                 public static bool IsValid(string value) => !string.IsNullOrEmpty(value);
                             }
                             """;

        const string expected = """
                                  // <auto-generated />
                                  #nullable enable
                                  
                                  namespace Test
                                  {
                                      public static class NotNullOrEmptyRuleExtensions
                                      {
                                          [global::ValiCraft.Abstractions.Attributes.MapToValidationRule(
                                              validationRuleType: typeof(global::Test.NotNullOrEmptyRule),
                                              validationRuleGenericFormat: "")]
                                          public static global::ValiCraft.Abstractions.BuilderTypes.IValidationRuleBuilderType<TRequest, TPropertyType> IsNotNullOrEmpty<TRequest, TPropertyType>(
                                              this global::ValiCraft.Abstractions.BuilderTypes.IBuilderType<TRequest, TPropertyType> builder) where TRequest : class
                                              => throw new global::System.NotImplementedException("Never gets called");
                                      }
                                  }
                                  """;

        using var assertionScope = new AssertionScope();
        
        var options = IncrementalGeneratorTestOptions.CreateDefault(typeof(Validator<>));
        
        new IncrementalGeneratorAdapter(options)
            .GetGeneratedTrees<ValidationRuleExtensionGenerator>([input], [TrackingSteps.ValidationRuleInfoResultTrackingName])
            .AssertHasNoDiagnostics()
            .AssertOutputs(expected);
    }

    [Fact]
    public void ShouldGenerateValidationRuleExtensionsForGenerics()
    {
        const string input = """
                             using ValiCraft.Abstractions;
                             using ValiCraft.Abstractions.Attributes;
                             using System.Numerics;
                             
                             namespace Test;
                             
                             [GenerateRuleExtension("IsGenericRule")]
                             public class GenericRule<TPropertyType, TParam1, TParam2> : IValidationRule<TPropertyType, TParam1, TParam2>
                                 where TParam1 : INumber<TParam1>
                             {
                                 public static bool IsValid(TPropertyType propertyType, TParam1 param1, TParam2 param2) => true;
                             }
                             """;

        const string expected = """
                                  // <auto-generated />
                                  #nullable enable
                                  
                                  namespace Test
                                  {
                                      public static class GenericRuleExtensions
                                      {
                                          [global::ValiCraft.Abstractions.Attributes.MapToValidationRule(
                                              validationRuleType: typeof(global::Test.GenericRule<,,>),
                                              validationRuleGenericFormat: "<{0}, {1}, {2}>")]
                                          public static global::ValiCraft.Abstractions.BuilderTypes.IValidationRuleBuilderType<TRequest, TPropertyType> IsGenericRule<TRequest, TPropertyType, TParam1, TParam2>(
                                              this global::ValiCraft.Abstractions.BuilderTypes.IBuilderType<TRequest, TPropertyType> builder, TParam1 param1, TParam2 param2) where TRequest : class where TParam1 : global::System.Numerics.INumber<TParam1>
                                              => throw new global::System.NotImplementedException("Never gets called");
                                      }
                                  }
                                  """;

        using var assertionScope = new AssertionScope();

        var options = IncrementalGeneratorTestOptions.CreateDefault(typeof(Validator<>));

        new IncrementalGeneratorAdapter(options)
            .GetGeneratedTrees<ValidationRuleExtensionGenerator>([input], [TrackingSteps.ValidationRuleInfoResultTrackingName])
            .AssertHasNoDiagnostics()
            .AssertOutputs(expected);
    }
}