using AwesomeAssertions.Execution;
using ValiCraft.Abstractions;
using ValiCraft.TestHelpers;

namespace ValiCraft.Rules.Generator.Tests;

public class ValidationRuleExtensionGeneratorTests
{
    [Fact]
    public void ShouldGenerateValidationRuleExtensions()
    {
        const string input = """
                             using ValiCraft.Abstractions;
                             using ValiCraft.Abstractions.Attributes;
                             
                             namespace Test;
                             
                             [GenerateRuleExtension("IsNotNullOrEmpty")]
                             public class NotNullOrEmptyRule : IValidationRule<string?>
                             {
                                 public static bool IsValid(string value) => !string.IsNullOrEmpty(value);
                             }
                             """;

        const string expected = """
                                  // <auto-generated />
                                  #nullable enable
                                  
                                  namespace Test
                                  {
                                      public static class NotNullOrEmptyRuleExtensions
                                      {
                                          [global::ValiCraft.Abstractions.Attributes.MapToValidationRule(typeof(NotNullOrEmptyRule))]
                                          public static IValidationRuleBuilderType<TRequest, TPropertyType> IsNotNullOrEmpty<TRequest, TPropertyType>(
                                              this IBuilderType<TRequest, TPropertyType> builder) 
                                              => throw new NotImplementedException("Never gets called");
                                      }
                                  }
                                  """;

        using var assertionScope = new AssertionScope();
        
        var options = IncrementalGeneratorTestOptions.CreateDefault(typeof(Validator<>));
        
        new IncrementalGeneratorAdapter(options)
            .GetGeneratedTrees<ValidationRuleExtensionGenerator>([input], [TrackingSteps.ValidationRuleInfoResultTrackingName])
            .AssertHasNoDiagnostics()
            .AssertOutputs(expected);
    }
}