using System.Diagnostics.CodeAnalysis;
using ValiCraft.Generator.Tests.Helpers;

namespace ValiCraft.Generator.Tests.StaticGeneratorTests;

public class SingleEnsureEachRuleChain_DirectRuleTest : IncrementalGeneratorTestBase<ValiCraftGenerator>
{
    [StringSyntax("CSharp")] private const string InputRequests = """
                                                             using System.Collections.Generic;

                                                             namespace Test.Requests;

                                                             public class Request
                                                             {
                                                                 public required List<string> Tags { get; set; }
                                                             }
                                                             """;

    [StringSyntax("CSharp")] private const string InputValidatorsToGenerate = """
                                                                         using Test.Requests;
                                                                         using ValiCraft;
                                                                         using ValiCraft.Attributes;
                                                                         using ValiCraft.BuilderTypes;

                                                                         namespace Test.Validators;

                                                                         [GenerateValidator]
                                                                         public partial class RequestValidator : StaticValidator<Request>
                                                                         {
                                                                             protected override void DefineRules(IValidationRuleBuilder<Request> builder)
                                                                             {
                                                                                 builder.EnsureEach(p => p.Tags)
                                                                                     .IsNotNullOrWhiteSpace();
                                                                             }
                                                                         }
                                                                         """;

    [StringSyntax("CSharp")] private const string ExpectedValidators = """
                                                                       // <auto-generated />
                                                                       #nullable enable

                                                                       using Test.Requests;
                                                                       using ValiCraft;
                                                                       using ValiCraft.Attributes;
                                                                       using ValiCraft.BuilderTypes;

                                                                       namespace Test.Validators
                                                                       {
                                                                           /// <summary>
                                                                           /// Generated static validator for <see cref="global::Test.Requests.Request"/>.
                                                                           /// </summary>
                                                                           public partial class RequestValidator : global::ValiCraft.IStaticValidator<global::Test.Requests.Request>
                                                                           {
                                                                               /// <inheritdoc />
                                                                               public static global::ValiCraft.ValidationErrors? Validate(global::Test.Requests.Request request)
                                                                               {
                                                                                   var errors = RunValidationLogic(request, null);

                                                                                   if (errors is null) return null;

                                                                                   return new global::ValiCraft.ValidationErrors
                                                                                   {
                                                                                       Code = "RequestErrors",
                                                                                       Message = "One or more validation errors occurred.",
                                                                                       Severity = global::ValiCraft.ErrorSeverity.Error,
                                                                                       Errors = errors
                                                                                   };
                                                                               }

                                                                               /// <inheritdoc />
                                                                               [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                                                                               public static global::System.Collections.Generic.List<global::ValiCraft.ValidationError>? RunValidation(global::Test.Requests.Request request, string? inheritedTargetPath)
                                                                               {
                                                                                   return RunValidationLogic(request, inheritedTargetPath);
                                                                               }

                                                                               private static global::System.Collections.Generic.List<global::ValiCraft.ValidationError>? RunValidationLogic(global::Test.Requests.Request request, string? inheritedTargetPath)
                                                                               {
                                                                                   global::System.Collections.Generic.List<global::ValiCraft.ValidationError>? errors = null;

                                                                                   var index1 = 0;
                                                                                   foreach (var element in request.Tags)
                                                                                   {
                                                                                       if (!global::ValiCraft.Rules.NotNullOrWhiteSpace(element))
                                                                                       {
                                                                                           errors ??= new(1);
                                                                                           errors.Add(new global::ValiCraft.ValidationError
                                                                                           {
                                                                                               Code = nameof(global::ValiCraft.Rules.NotNullOrWhiteSpace),
                                                                                               Message = $"Tags must not be null or contain only whitespace.",
                                                                                               Severity = global::ValiCraft.ErrorSeverity.Error,
                                                                                               TargetName = "Tags",
                                                                                               TargetPath = $"{inheritedTargetPath}{(inheritedTargetPath is not null ? "Tags[{index1}]" : null)}",
                                                                                               AttemptedValue = element,
                                                                                           });
                                                                                       }
                                                                                       index1++;
                                                                                   }

                                                                                   return errors;
                                                                               }
                                                                           }
                                                                       }
                                                                       """;

    [Fact]
    public void ShouldGenerateStaticValidator()
    {
        AssertGenerator(inputs: [InputRequests, InputValidatorsToGenerate],
            outputs: [ExpectedValidators],
            diagnostics: [],
            assertInitialCompilation: true);
    }
}
