using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using ValiCraft.Generator.Extensions;
using ValiCraft.Generator.Models;
using ValiCraft.Generator.Types;

namespace ValiCraft.Generator.SourceProviders;

public static class ValidatorSourceProvider
{
    public static void EmitSourceCode(
        ImmutableArray<ProviderResult<ValidationRule>> validationRuleInfoResults,
        ImmutableArray<ProviderResult<ValidatorInfo>> validatorInfoResults,
        SourceProductionContext context)
    {
        var validRules = validationRuleInfoResults
            .Where(r => r.Value is not null)
            .Select(r => r.Value!)
            .ToArray();

        foreach (var validatorInfoResult in validatorInfoResults)
        {
            if (HasReportedDiagnostics(validatorInfoResult, context) ||
                !TryLinkWeakSemanticRules(validatorInfoResult, validRules, context, out var validatorInfo))
            {
                continue;
            }

            var sourceCode = GenerateSourceCode(validatorInfo);

            context.AddSource($"{validatorInfoResult.Value!.Class.Name}.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
        }
    }

    private static bool HasReportedDiagnostics(
        ProviderResult<ValidatorInfo> validatorInfoResult,
        SourceProductionContext context)
    {
        if (validatorInfoResult.Diagnostics is not { Count: > 0 })
        {
            return false;
        }
        
        foreach (var diagnostic in validatorInfoResult.Diagnostics)
        {
            context.ReportDiagnostic(diagnostic.CreateDiagnostic());
        }

        return true;
    }

    private static bool TryLinkWeakSemanticRules(
        ProviderResult<ValidatorInfo> validatorInfoResult,
        ValidationRule[] validRules,
        SourceProductionContext context,
        out ValidatorInfo validatorInfo)
    {
        validatorInfo = validatorInfoResult.Value!;
        var rules = new List<Rule>(validatorInfo.Rules.Count);
        
        foreach (var rule in validatorInfo.Rules)
        {
            if (rule.SemanticMode is SemanticMode.WeakSemanticMode)
            {
                var matchedValidationRule = rule.MapToValidationRule(validRules);

                if (matchedValidationRule is null)
                {
                    var diagnostics = DefinedDiagnostics.UnrecognizableRuleInvocation(rule.Location.ToLocation());
                    context.ReportDiagnostic(diagnostics.CreateDiagnostic());
                    
                    return false;
                }

                rules.Add(rule.EnrichRuleFromValidationRule(matchedValidationRule));
                continue;
            }
            
            rules.Add(rule);
        }

        validatorInfo = validatorInfo with
        {
            Rules = rules.ToEquatableImmutableArray()
        };
        
        return true;
    }

    private static string GenerateSourceCode(ValidatorInfo validatorInfo)
    {
        return $$"""
                 // <auto-generated />
                 #nullable enable

                 namespace {{validatorInfo.Class.Namespace}}
                 {
                     {{validatorInfo.Class.Modifiers}} class {{validatorInfo.Class.Name}} : global::{{KnownNames.Interfaces.IValidator}}<{{validatorInfo.RequestTypeName}}>
                     {
                         public global::{{KnownNames.Types.Validation}}<{{validatorInfo.RequestTypeName}}> Validate({{validatorInfo.RequestTypeName}} request)
                         {
                             global::System.Collections.Generic.List<global::{{KnownNames.Types.Error}}>? errors = null;
                             
                 {{GenerateCodeForRules(validatorInfo.Rules)}}

                             return errors is not null
                                 ? global::{{KnownNames.Types.Validation}}<{{validatorInfo.RequestTypeName}}>.Failure(errors)
                                 : global::{{KnownNames.Types.Validation}}<{{validatorInfo.RequestTypeName}}>.Success(request);
                         }
                     }
                 }
                 """;
    }

    private static string GenerateCodeForRules(EquatableArray<Rule> rules)
    {
        var rulesCode = new List<string>();
        var assignedErrorsCount = rules.Count;
        
        foreach (var rule in rules)
        {
            rulesCode.Add(rule.GenerateCodeForRule(assignedErrorsCount));
            assignedErrorsCount--;
        }
        
        return string.Join("\r\n", rulesCode);
    }
}