using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using ValiCraft.Generator.Models;
using ValiCraft.Generator.Types;

namespace ValiCraft.Generator.SourceProviders;

public static class ValidationRuleExtensionSourceProvider
{
    public static void EmitSourceCode(
        ImmutableArray<ProviderResult<ValidationRuleInfo>> validationRuleInfoResults,
        SourceProductionContext context)
    {
        foreach (var validationRuleInfoResult in validationRuleInfoResults)
        {
            if (validationRuleInfoResult.Diagnostics is { Count: > 0 })
            {
                foreach (var diagnostic in validationRuleInfoResult.Diagnostics) context.ReportDiagnostic(diagnostic);

                continue;
            }

            var validationRule = validationRuleInfoResult.Value!;
            var mapToValidationRuleData = validationRule.GetMapToValidationRuleData();

            var attributesBuilder = new StringBuilder();

            if (validationRule.DefaultMessage is not null)
                attributesBuilder.Append($"""
                                          [global::{FullyQualifiedNames.Attributes.DefaultMessage}({validationRule.DefaultMessage})]
                                              
                                          """);

            foreach (var rulePlaceholder in validationRule.RulePlaceholders)
                attributesBuilder.Append($"""
                                          [global::{FullyQualifiedNames.Attributes.RulePlaceholder}("{rulePlaceholder.PlaceholderName}", "{rulePlaceholder.ParameterName}")]
                                              
                                          """);

            var sourceCode = $$"""
                               // <auto-generated />
                               #nullable enable

                               namespace {{validationRule.Class.Namespace}}
                               {
                                   {{attributesBuilder}}{{validationRule.Class.Accessibility}} static class {{validationRule.Class.Name}}Extensions
                                   {
                                       [global::{{FullyQualifiedNames.Attributes.MapToValidationRule}}(typeof({{mapToValidationRuleData.FullyQualifiedUnboundedName}}), "{{mapToValidationRuleData.ValidationRuleGenericFormat}}")]
                                       {{validationRule.Class.Accessibility}} static global::{{FullyQualifiedNames.Interfaces.IValidationRuleBuilderType}}<TRequest, TPropertyType> {{validationRule.NameForExtensionMethod}}<{{validationRule.GetGenericArgumentsForExtensionMethod()}}>(
                                           {{GetMethodParameters(validationRule)}}) {{GetFullWhereClause(validationRule)}}
                                           => throw new global::System.NotImplementedException("Never gets called");
                                   }
                               }
                               """;

            context.AddSource($"{validationRule.Class.Name}Extensions.g.cs",
                SourceText.From(sourceCode, Encoding.UTF8));
        }
    }

    private static string GetFullWhereClause(ValidationRuleInfo validationRuleInfo)
    {
        var clauses = new List<string> { "where TRequest : class" };

        // Get all the constraint clauses we discovered from the rule's generic parameters.
        var additionalClauses = validationRuleInfo.Class.GenericParameters
            .Select(p => p.Constraints)
            .Where(c => !string.IsNullOrEmpty(c));

        clauses.AddRange(additionalClauses);

        return string.Join(" ", clauses);
    }

    private static string GetMethodParameters(ValidationRuleInfo validationRuleInfo)
    {
        return validationRuleInfo.GetParametersForExtensionMethod(
            $"this global::{FullyQualifiedNames.Interfaces.IBuilderType}<TRequest, TPropertyType> builder");
    }
}