using System.Linq.Expressions;
using AwesomeAssertions.Execution;
using ValiCraft.Abstractions;
using ValiCraft.Rules;
using ValiCraft.TestHelpers;

namespace ValiCraft.Providers.LitePrimitives.Generator.Tests;

public class ValidatorGeneratorTests
{
    [Fact]
    public void ShouldGenerateValidator()
    {
        const string user = """
                            namespace Test;

                            public class User
                            {
                                public string? Name { get; set; }
                                public int Age { get; set; }
                            }
                            """;
        
        const string input = """
                             using ValiCraft.Abstractions;
                             using ValiCraft.Abstractions.Attributes;
                             using ValiCraft.Rules;
                             
                             namespace Test;
                             
                             [GenerateValidator]
                             public partial class UserValidator : Validator<User>
                             {
                                 protected override void DefineRules(IValidationRuleBuilder<User> builder)
                                 {
                                     builder.Ensure(x => x.Name)
                                         .Is<NotEmpty>()
                                         .Is<NotNull<string>>().WithMessage("{PropertyName} is required");
                                 }
                             }
                             """;

        const string expected = """
                                  // <auto-generated />
                                  #nullable enable
                                  
                                  namespace Test
                                  {
                                      public partial class UserValidator : global::ValiCraft.Providers.LitePrimitives.IValidator<global::Test.User>
                                      {
                                          public global::LitePrimitives.Validation<global::Test.User> Validate(global::Test.User request)
                                          {
                                              return global::LitePrimitives.Validation<global::Test.User>.Success(request);
                                          }
                                      }
                                  }
                                  """;

        using var assertionScope = new AssertionScope();
        
        var options = IncrementalGeneratorTestOptions.CreateDefault(
            typeof(Validator<>),
            typeof(IValidator<>),
            typeof(NotNull<>),
            typeof(Expression<>));
        
        new IncrementalGeneratorAdapter(options)
            .GetGeneratedTrees<ValidatorGenerator>([user, input], [TrackingSteps.ValidatorInfoResultTrackingName])
            .AssertHasNoDiagnostics()
            .AssertOutputs(expected);
    }
}