using System.Linq.Expressions;
using AwesomeAssertions.Execution;
using ValiCraft.Abstractions;
using ValiCraft.Generator.Shared;
using ValiCraft.Rules;
using ValiCraft.TestHelpers;

namespace ValiCraft.Providers.LitePrimitives.Generator.Tests;

public class ValidatorGeneratorTests
{
    [Fact]
    public void ShouldGenerateValidator()
    {
        const string user = """
                            namespace Test;

                            public class User
                            {
                                public string? Name { get; set; }
                                public int Age { get; set; }
                            }
                            """;

        const string validationRulesInput = """
                             using ValiCraft.Abstractions;
                             using ValiCraft.Abstractions.Attributes;
                             
                             namespace Test.Rules;
                             
                             [GenerateRuleExtension("IsGenericRule")]
                             public class GenericRule<TPropertyType, TParam1, TParam2> : IValidationRule<TPropertyType, TParam1, TParam2>
                             {
                                 public static bool IsValid(TPropertyType propertyType, TParam1 param1, TParam2 param2) => true;
                             }
                             """;
        
        const string validatiorInput = """
                             using ValiCraft.Abstractions;
                             using ValiCraft.Abstractions.Attributes;
                             using ValiCraft.Rules;
                             using Test.Rules;
                             
                             namespace Test;
                             
                             [GenerateValidator]
                             public partial class UserValidator : Validator<User>
                             {
                                 protected override void DefineRules(IValidationRuleBuilder<User> builder)
                                 {
                                     builder.Ensure(x => x.Name)
                                         .IsGenericRule(1, false);
                                 }
                             }
                             """;

        const string validationRulesExpected = """
                                  // <auto-generated />
                                  #nullable enable
                                  
                                  namespace Test.Rules
                                  {
                                      public static class GenericRuleExtensions
                                      {
                                          [global::ValiCraft.Abstractions.Attributes.MapToValidationRule(typeof(global::Test.Rules.GenericRule<,,>))]
                                          public static global::ValiCraft.Abstractions.BuilderTypes.IValidationRuleBuilderType<TRequest, TPropertyType> IsGenericRule<TRequest, TPropertyType, TParam1, TParam2>(
                                              this global::ValiCraft.Abstractions.BuilderTypes.IBuilderType<TRequest, TPropertyType> builder, TParam1 param1, TParam2 param2) where TRequest : class
                                              => throw new global::System.NotImplementedException("Never gets called");
                                      }
                                  }
                                  """;

        const string validatorExpected = """
                                  // <auto-generated />
                                  #nullable enable
                                  
                                  namespace Test
                                  {
                                      public partial class UserValidator : global::ValiCraft.Providers.LitePrimitives.IValidator<global::Test.User>
                                      {
                                          public global::LitePrimitives.Validation<global::Test.User> Validate(global::Test.User request)
                                          {
                                              global::System.Collections.Generic.List<global::LitePrimitives.Error> errors = new(5);
                                              
                                              if (global::Test.Rules.GenericRule<string, int, bool>.IsValid(request.Name, 1, false))
                                              {
                                                  global::LitePrimitives.Error error = global::LitePrimitives.Error.Validation(nameof(global::Test.Rules.GenericRule<string, int, bool>), "An error has occurred");
                                                  errors.Add(error);
                                              }


                                              return errors.Count > 0
                                                  ? global::LitePrimitives.Validation<global::Test.User>.Failure(errors)
                                                  : global::LitePrimitives.Validation<global::Test.User>.Success(request);
                                          }
                                      }
                                  }
                                  """;

        using var assertionScope = new AssertionScope();
        
        var options = IncrementalGeneratorTestOptions.CreateDefault(
            typeof(Validator<>),
            typeof(IValidator<>),
            typeof(NotNull<>),
            typeof(Expression<>));
        
        new IncrementalGeneratorAdapter(options)
            .GetGeneratedTrees<ValidatorGenerator>([user, validationRulesInput, validatiorInput], [TrackingSteps.ValidatorInfoResultTrackingName])
            .AssertHasNoDiagnostics()
            .AssertOutputs(validationRulesExpected, validatorExpected);
    }
    
    
    [Fact]
    public void ShouldGenerateValidatorForSingleGeneric()
    {
        const string user = """
                            namespace Test;

                            public class User
                            {
                                public string? Name { get; set; }
                                public int Age { get; set; }
                            }
                            """;

        const string validationRulesInput = """
                             using ValiCraft.Abstractions;
                             using ValiCraft.Abstractions.Attributes;
                             
                             namespace Test.Rules;
                             
                             [GenerateRuleExtension("IsGenericRule")]
                             public class GenericRule<T> : IValidationRule<T?>
                             {
                                 public static bool IsValid(T? value) => true;
                             }
                             """;
        
        const string validatiorInput = """
                             using ValiCraft.Abstractions;
                             using ValiCraft.Abstractions.Attributes;
                             using ValiCraft.Rules;
                             using Test.Rules;
                             
                             namespace Test;
                             
                             [GenerateValidator]
                             public partial class UserValidator : Validator<User>
                             {
                                 protected override void DefineRules(IValidationRuleBuilder<User> builder)
                                 {
                                     builder.Ensure(x => x.Name)
                                         .IsGenericRule();
                                 }
                             }
                             """;

        const string validationRulesExpected = """
                                  // <auto-generated />
                                  #nullable enable
                                  
                                  namespace Test.Rules
                                  {
                                      public static class GenericRuleExtensions
                                      {
                                          [global::ValiCraft.Abstractions.Attributes.MapToValidationRule(typeof(global::Test.Rules.GenericRule<>))]
                                          public static global::ValiCraft.Abstractions.BuilderTypes.IValidationRuleBuilderType<TRequest, TPropertyType> IsGenericRule<TRequest, TPropertyType>(
                                              this global::ValiCraft.Abstractions.BuilderTypes.IBuilderType<TRequest, TPropertyType> builder) where TRequest : class
                                              => throw new global::System.NotImplementedException("Never gets called");
                                      }
                                  }
                                  """;

        const string validatorExpected = """
                                  // <auto-generated />
                                  #nullable enable
                                  
                                  namespace Test
                                  {
                                      public partial class UserValidator : global::ValiCraft.Providers.LitePrimitives.IValidator<global::Test.User>
                                      {
                                          public global::LitePrimitives.Validation<global::Test.User> Validate(global::Test.User request)
                                          {
                                              global::System.Collections.Generic.List<global::LitePrimitives.Error> errors = new(5);
                                              
                                              if (global::Test.Rules.GenericRule<string>.IsValid(request.Name))
                                              {
                                                  global::LitePrimitives.Error error = global::LitePrimitives.Error.Validation(nameof(global::Test.Rules.GenericRule<string>), "An error has occurred");
                                                  errors.Add(error);
                                              }


                                              return errors.Count > 0
                                                  ? global::LitePrimitives.Validation<global::Test.User>.Failure(errors)
                                                  : global::LitePrimitives.Validation<global::Test.User>.Success(request);
                                          }
                                      }
                                  }
                                  """;

        using var assertionScope = new AssertionScope();
        
        var options = IncrementalGeneratorTestOptions.CreateDefault(
            typeof(Validator<>),
            typeof(IValidator<>),
            typeof(NotNull<>),
            typeof(Expression<>));
        
        new IncrementalGeneratorAdapter(options)
            .GetGeneratedTrees<ValidatorGenerator>([user, validationRulesInput, validatiorInput], [TrackingSteps.ValidatorInfoResultTrackingName])
            .AssertHasNoDiagnostics()
            .AssertOutputs(validationRulesExpected, validatorExpected);
    }
}