using System.Diagnostics.CodeAnalysis;
using ValiCraft.Generator.Tests.Helpers;

namespace ValiCraft.Generator.Tests;

public class VALC302Tests : IncrementalGeneratorTestBase<ValiCraftGenerator>
{
    [StringSyntax("CSharp")] private const string InputRequests = """
                                                                  namespace Test.Requests;
                                                                  
                                                                  public class User
                                                                  {
                                                                      public string? Name { get; set; }    
                                                                  }
                                                                  """;
    
    [StringSyntax("CSharp")] private const string InputValidatorWithInstanceField = """
                                                                   using Test.Requests;
                                                                   using ValiCraft;
                                                                   using ValiCraft.Attributes;
                                                                   using ValiCraft.BuilderTypes;
                                                                   
                                                                   namespace Test.Validators;
                                                                   
                                                                   [GenerateValidator]
                                                                   public partial class UserValidator : StaticValidator<User>
                                                                   {
                                                                       private readonly string _prefix = "test";
                                                                   
                                                                       protected override void DefineRules(IValidationRuleBuilder<User> builder)
                                                                       {
                                                                           builder.Ensure(x => x.Name)
                                                                               .IsNotNullOrEmpty();
                                                                       }
                                                                   }
                                                                   """;
    
    [StringSyntax("CSharp")] private const string InputValidatorWithStaticField = """
                                                                   using Test.Requests;
                                                                   using ValiCraft;
                                                                   using ValiCraft.Attributes;
                                                                   using ValiCraft.BuilderTypes;
                                                                   
                                                                   namespace Test.Validators;
                                                                   
                                                                   [GenerateValidator]
                                                                   public partial class UserValidator : StaticValidator<User>
                                                                   {
                                                                       private static readonly string Prefix = "test";
                                                                   
                                                                       protected override void DefineRules(IValidationRuleBuilder<User> builder)
                                                                       {
                                                                           builder.Ensure(x => x.Name)
                                                                               .IsNotNullOrEmpty();
                                                                       }
                                                                   }
                                                                   """;
    
    [StringSyntax("CSharp")] private const string ExpectedValidators = """
                                                                   // <auto-generated />
                                                                   #nullable enable

                                                                   using Test.Requests;
                                                                   using ValiCraft;
                                                                   using ValiCraft.Attributes;
                                                                   using ValiCraft.BuilderTypes;

                                                                   namespace Test.Validators
                                                                   {
                                                                       /// <summary>
                                                                       /// Generated static validator for <see cref="global::Test.Requests.User"/>.
                                                                       /// </summary>
                                                                       public partial class UserValidator : global::ValiCraft.IStaticValidator<global::Test.Requests.User>
                                                                       {
                                                                           /// <inheritdoc />
                                                                           public static global::ErrorCraft.ValidationErrors? Validate(global::Test.Requests.User request)
                                                                           {
                                                                               var errors = RunValidation(request, null);

                                                                               if (errors is null) return null;

                                                                               return new global::ErrorCraft.ValidationErrors
                                                                               {
                                                                                   Code = "UserErrors",
                                                                                   Message = "One or more validation errors occurred.",
                                                                                   Severity = global::ErrorCraft.ErrorSeverity.Error,
                                                                                   Errors = errors
                                                                               };
                                                                           }

                                                                           /// <inheritdoc />
                                                                           [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                                                                           public static global::ErrorCraft.ValidationErrors? Validate(global::Test.Requests.User request, string? inheritedTargetPath)
                                                                           {
                                                                               var errors = RunValidation(request, inheritedTargetPath);

                                                                               if (errors is null) return null;

                                                                               return new global::ErrorCraft.ValidationErrors
                                                                               {
                                                                                   Code = "UserErrors",
                                                                                   Message = "One or more validation errors occurred.",
                                                                                   Severity = global::ErrorCraft.ErrorSeverity.Error,
                                                                                   Errors = errors
                                                                               };
                                                                           }

                                                                           /// <summary>
                                                                           /// Runs the validation logic and returns the raw error list. This method is intended for internal use by nested validators.
                                                                           /// </summary>
                                                                           [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                                                                           public static global::System.Collections.Generic.List<global::ErrorCraft.IValidationError>? RunValidation(global::Test.Requests.User request, string? inheritedTargetPath)
                                                                           {
                                                                               global::System.Collections.Generic.List<global::ErrorCraft.IValidationError>? errors = null;

                                                                               if (!global::ValiCraft.Rules.NotNullOrEmpty(request.Name))
                                                                               {
                                                                                   errors ??= new(1);
                                                                                   errors.Add(new global::ErrorCraft.ValidationError<string?>
                                                                                   {
                                                                                       Code = nameof(global::ValiCraft.Rules.NotNullOrEmpty),
                                                                                       Message = $"Name must not be null or empty.",
                                                                                       Severity = global::ErrorCraft.ErrorSeverity.Error,
                                                                                       TargetName = "Name",
                                                                                       TargetPath = $"{inheritedTargetPath}Name",
                                                                                       AttemptedValue = request.Name,
                                                                                   });
                                                                               }

                                                                               return errors;
                                                                           }
                                                                       }
                                                                   }
                                                                   """;

    [Fact]
    public void ShouldReportVALC302_WhenStaticValidatorHasInstanceField()
    {
        AssertGenerator(inputs: [InputRequests, InputValidatorWithInstanceField], 
            outputs: [],
            diagnostics: ["Static validators cannot have instance fields. Field '_prefix' should be removed or made static."],
            assertTrackingSteps: false);
    }
    
    [Fact]
    public void ShouldNotReportVALC302_WhenStaticValidatorHasStaticField()
    {
        // Static fields are allowed - validation should pass
        AssertGenerator(inputs: [InputRequests, InputValidatorWithStaticField],
            outputs: [ExpectedValidators],
            diagnostics: [],
            assertTrackingSteps: false);
    }
}
