using System.Diagnostics.CodeAnalysis;
using ValiCraft.Generator.Tests.Helpers;

namespace ValiCraft.Generator.Tests;

public class VALC204Tests : IncrementalGeneratorTestBase<ValiCraftGenerator>
{
    [StringSyntax("CSharp")] private const string InputRequests = """
                                                                  using System.Collections.Generic;
                                                                  
                                                                  namespace Test.Requests;
                                                                  
                                                                  public class Order
                                                                  {
                                                                      public List<LineItem> LineItems { get; set; } = [];    
                                                                  }
                                                                  
                                                                  public class LineItem
                                                                  {
                                                                      public string? SKU { get; set; }
                                                                  }
                                                                  """;
    
    [StringSyntax("CSharp")] private const string InputValidationRules = """
                                                          using System;
                                                          using ValiCraft;
                                                          using ValiCraft.Attributes;
                                                          using ValiCraft.BuilderTypes;
                                                          
                                                          namespace Test.Rules;
                                                          
                                                          [GenerateRuleExtension("IsNotNull")]
                                                          [DefaultMessage("'{TargetName}' must not be null.")]
                                                          public class NotNullRule<T> : IValidationRule<T?>
                                                          {
                                                              public static bool IsValid(T? value) => value is not null;
                                                          }
                                                          """;
    
    [StringSyntax("CSharp")] private const string InputValidator = """
                                                                   using Test.Rules;
                                                                   using Test.Requests;
                                                                   using ValiCraft;
                                                                   using ValiCraft.Attributes;
                                                                   using ValiCraft.BuilderTypes;
                                                                   
                                                                   namespace Test.Validators;
                                                                   
                                                                   [GenerateValidator]
                                                                   public partial class OrderValidator : Validator<Order>
                                                                   {
                                                                       protected override void DefineRules(IValidationRuleBuilder<Order> builder)
                                                                       {
                                                                           builder.EnsureEach(x => x.LineItems, l => DefineFavouriteNumbersRules(l));
                                                                       }
                                                                       
                                                                       private void DefineFavouriteNumbersRules(IValidationRuleBuilder<LineItem> builder)
                                                                       {
                                                                           builder.Ensure(x => x.SKU).IsNotNull();
                                                                       }
                                                                   }
                                                                   """;
    
    [StringSyntax("CSharp")] private const string ExpectedNotNullExtensions = """
                                                                              // <auto-generated />
                                                                              #nullable enable
                                                                              
                                                                              namespace Test.Rules
                                                                              {
                                                                                  [global::ValiCraft.Attributes.DefaultMessage("'{TargetName}' must not be null.")]
                                                                                  public static class NotNullRuleExtensions
                                                                                  {
                                                                                      [global::ValiCraft.Attributes.MapToValidationRule(typeof(global::Test.Rules.NotNullRule<>), "<{0}>")]
                                                                                      public static global::ValiCraft.BuilderTypes.IValidationRuleBuilderType<TRequest, TTargetType> IsNotNull<TRequest, TTargetType>(
                                                                                          this global::ValiCraft.BuilderTypes.IBuilderType<TRequest, TTargetType> builder) where TRequest : class
                                                                                          => throw new global::System.NotImplementedException("Never gets called");

                                                                                      [global::ValiCraft.Attributes.MapToValidationRule(typeof(global::Test.Rules.NotNullRule<>), "<{0}>")]
                                                                                      public static global::ValiCraft.AsyncBuilderTypes.IAsyncValidationRuleBuilderType<TRequest, TTargetType> IsNotNull<TRequest, TTargetType>(
                                                                                          this global::ValiCraft.AsyncBuilderTypes.IAsyncBuilderType<TRequest, TTargetType> builder) where TRequest : class
                                                                                          => throw new global::System.NotImplementedException("Never gets called");
                                                                                  }
                                                                              }
                                                                              """;
    
    [Fact]
    public void ShouldReportVALC204()
    {
        AssertGenerator(inputs: [InputRequests, InputValidationRules, InputValidator], 
            outputs: [ExpectedNotNullExtensions],
            diagnostics: [$"EnsureEach expects a lambda as the last parameter."],
            assertTrackingSteps: false);
    }
}