using System.Diagnostics.CodeAnalysis;
using ValiCraft.Generator.Tests.Helpers;

namespace ValiCraft.Generator.Tests.GeneratorTests;

public class NestedClass_MultipleLevelsTest : IncrementalGeneratorTestBase<ValiCraftGenerator>
{
    [StringSyntax("CSharp")] private const string InputRequests = """
                                                             using System;
                                                             using System.Collections.Generic;

                                                             namespace Test.Requests;

                                                             public class Order
                                                             {
                                                                 public required string OrderNumber { get; set; }
                                                                 public decimal OrderTotal { get; set; }
                                                                 public string? ShippingReference { get; set; }
                                                             }
                                                             """;

    [StringSyntax("CSharp")] private const string InputValidatorsToGenerate = """
                                                                         using Test.Requests;
                                                                         using ValiCraft;
                                                                         using ValiCraft.Attributes;
                                                                         using ValiCraft.BuilderTypes;

                                                                         namespace Test.Validators;

                                                                         public partial class Feature
                                                                         {
                                                                             public partial class Nested
                                                                             {
                                                                                 [GenerateValidator]
                                                                                 public partial class OrderValidator : Validator<Order>
                                                                                 {
                                                                                     protected override void DefineRules(IValidationRuleBuilder<Order> orderBuilder)
                                                                                     {
                                                                                         orderBuilder.Ensure(x => x.OrderTotal)
                                                                                            .Is(x => Rules.GreaterThan(x, 0M) == true);
                                                                                     }
                                                                                 }
                                                                             }
                                                                         }
                                                                         """;

    [StringSyntax("CSharp")] private const string ExpectedValidators = """
                                                                       // <auto-generated />
                                                                       #nullable enable
                                                                       
                                                                       using Test.Requests;
                                                                       using ValiCraft;
                                                                       using ValiCraft.Attributes;
                                                                       using ValiCraft.BuilderTypes;
                                                                       
                                                                       namespace Test.Validators
                                                                       {
                                                                           public partial class Feature
                                                                           {
                                                                               public partial class Nested
                                                                               {
                                                                                   /// <summary>
                                                                                   /// Generated validator for <see cref="global::Test.Requests.Order"/>.
                                                                                   /// </summary>
                                                                                   public partial class OrderValidator : global::ValiCraft.IValidator<global::Test.Requests.Order>
                                                                                   {
                                                                                       /// <inheritdoc />
                                                                                       public global::ValiCraft.ValidationErrors? Validate(global::Test.Requests.Order request)
                                                                                       {
                                                                                           var errors = RunValidationLogic(request, null);

                                                                                           if (errors is null) return null;

                                                                                           return new global::ValiCraft.ValidationErrors
                                                                                           {
                                                                                               Code = "OrderErrors",
                                                                                               Message = "One or more validation errors occurred.",
                                                                                               Severity = global::ValiCraft.ErrorSeverity.Error,
                                                                                               Errors = errors
                                                                                           };
                                                                                       }

                                                                                       /// <inheritdoc />
                                                                                       [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                                                                                       public global::System.Collections.Generic.List<global::ValiCraft.ValidationError>? RunValidation(global::Test.Requests.Order request, string? inheritedTargetPath)
                                                                                       {
                                                                                           return RunValidationLogic(request, inheritedTargetPath);
                                                                                       }

                                                                                       private global::System.Collections.Generic.List<global::ValiCraft.ValidationError>? RunValidationLogic(global::Test.Requests.Order request, string? inheritedTargetPath)
                                                                                       {
                                                                                           global::System.Collections.Generic.List<global::ValiCraft.ValidationError>? errors = null;
                                                                       
                                                                                           if (!(Rules.GreaterThan(request.OrderTotal, 0M) == true))
                                                                                           {
                                                                                               errors ??= new(1);
                                                                                               errors.Add(new global::ValiCraft.ValidationError
                                                                                               {
                                                                                                   Code = "Is",
                                                                                                   Message = $"'Order Total' doesn't satisfy the condition",
                                                                                                   Severity = global::ValiCraft.ErrorSeverity.Error,
                                                                                                   TargetName = "Order Total",
                                                                                                   TargetPath = $"{inheritedTargetPath}OrderTotal",
                                                                                                   AttemptedValue = request.OrderTotal,
                                                                                               });
                                                                                           }

                                                                                           return errors;
                                                                                       }
                                                                                   }
                                                                               }
                                                                           }
                                                                       }
                                                                       """;

    [Fact]
    public void ShouldGenerateValidator()
    {
        AssertGenerator(inputs: [InputRequests, InputValidatorsToGenerate], 
            outputs: [ExpectedValidators],
            diagnostics: [],
            assertInitialCompilation: true);
    }
}
