using System.Diagnostics.CodeAnalysis;
using ValiCraft.Generator.Tests.Helpers;

namespace ValiCraft.Generator.Tests.GeneratorTests;

public class NestedClass_SingleLevelTest : IncrementalGeneratorTestBase<ValiCraftGenerator>
{
    [StringSyntax("CSharp")] private const string InputRequests = """
                                                             using System;
                                                             using System.Collections.Generic;

                                                             namespace Test.Requests;

                                                             public class Order
                                                             {
                                                                 public required string OrderNumber { get; set; }
                                                                 public decimal OrderTotal { get; set; }
                                                                 public string? ShippingReference { get; set; }
                                                             }
                                                             """;

    [StringSyntax("CSharp")] private const string InputValidatorsToGenerate = """
                                                                         using Test.Requests;
                                                                         using ValiCraft;
                                                                         using ValiCraft.Attributes;
                                                                         using ValiCraft.BuilderTypes;
                                                                         using ErrorCraft;

                                                                         namespace Test.Validators;

                                                                         public partial class Feature
                                                                         {
                                                                             [GenerateValidator]
                                                                             public partial class OrderValidator : Validator<Order>
                                                                             {
                                                                                 protected override void DefineRules(IValidationRuleBuilder<Order> orderBuilder)
                                                                                 {
                                                                                     orderBuilder.Ensure(x => x.OrderTotal)
                                                                                        .Is(x => Rules.GreaterThan(x, 0M) == true);
                                                                                 }
                                                                             }
                                                                         }
                                                                         """;

    [StringSyntax("CSharp")] private const string ExpectedValidators = """
                                                                       // <auto-generated />
                                                                       #nullable enable
                                                                       
                                                                       using Test.Requests;
                                                                       using ValiCraft;
                                                                       using ValiCraft.Attributes;
                                                                       using ValiCraft.BuilderTypes;
                                                                       using ErrorCraft;
                                                                       
                                                                       namespace Test.Validators
                                                                       {
                                                                           public partial class Feature
                                                                           {
                                                                               /// <summary>
                                                                               /// Generated validator for <see cref="global::Test.Requests.Order"/>.
                                                                               /// </summary>
                                                                               public partial class OrderValidator : global::ValiCraft.IValidator<global::Test.Requests.Order>
                                                                               {
                                                                                   /// <inheritdoc />
                                                                                   public global::ErrorCraft.ValidationErrors? Validate(global::Test.Requests.Order request)
                                                                                   {
                                                                                       var errors = RunValidation(request, null);

                                                                                       if (errors is null) return null;

                                                                                       return new global::ErrorCraft.ValidationErrors
                                                                                       {
                                                                                           Code = "OrderErrors",
                                                                                           Message = "One or more validation errors occurred.",
                                                                                           Severity = global::ErrorCraft.ErrorSeverity.Error,
                                                                                           Errors = errors
                                                                                       };
                                                                                   }

                                                                                   /// <inheritdoc />
                                                                                   [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                                                                                   public global::ErrorCraft.ValidationErrors? Validate(global::Test.Requests.Order request, string? inheritedTargetPath)
                                                                                   {
                                                                                       var errors = RunValidation(request, inheritedTargetPath);

                                                                                       if (errors is null) return null;

                                                                                       return new global::ErrorCraft.ValidationErrors
                                                                                       {
                                                                                           Code = "OrderErrors",
                                                                                           Message = "One or more validation errors occurred.",
                                                                                           Severity = global::ErrorCraft.ErrorSeverity.Error,
                                                                                           Errors = errors
                                                                                       };
                                                                                   }

                                                                                   /// <summary>
                                                                                   /// Runs the validation logic and returns the raw error list. This method is intended for internal use by nested validators.
                                                                                   /// </summary>
                                                                                   [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                                                                                   public global::System.Collections.Generic.List<global::ErrorCraft.IValidationError>? RunValidation(global::Test.Requests.Order request, string? inheritedTargetPath)
                                                                                   {
                                                                                       global::System.Collections.Generic.List<global::ErrorCraft.IValidationError>? errors = null;
                                                                       
                                                                                       if (!(Rules.GreaterThan(request.OrderTotal, 0M) == true))
                                                                                       {
                                                                                           errors ??= new(1);
                                                                                           errors.Add(new global::ErrorCraft.ValidationError<decimal>
                                                                                           {
                                                                                               Code = "Is",
                                                                                               Message = $"'Order Total' doesn't satisfy the condition",
                                                                                               Severity = global::ErrorCraft.ErrorSeverity.Error,
                                                                                               TargetName = "Order Total",
                                                                                               TargetPath = $"{inheritedTargetPath}OrderTotal",
                                                                                               AttemptedValue = request.OrderTotal,
                                                                                           });
                                                                                       }

                                                                                       return errors;
                                                                                   }
                                                                               }
                                                                           }
                                                                       }
                                                                       """;

    [Fact]
    public void ShouldGenerateValidator()
    {
        AssertGenerator(inputs: [InputRequests, InputValidatorsToGenerate], 
            outputs: [ExpectedValidators],
            diagnostics: [],
            assertInitialCompilation: true);
    }
}
