using System.Diagnostics.CodeAnalysis;
using ValiCraft.Generator.Tests.Helpers;

namespace ValiCraft.Generator.Tests.GeneratorTests;

public class SingleEnsureEachRuleChain_DirectRule_IsLambdaTest : IncrementalGeneratorTestBase<ValiCraftGenerator>
{
    [StringSyntax("CSharp")] private const string InputRequests = """
                                                             using System.Collections.Generic;

                                                             namespace Test.Requests;

                                                             public class Request
                                                             {
                                                                 public required List<string> Tags { get; set; }
                                                             }
                                                             """;

    [StringSyntax("CSharp")] private const string InputValidatorsToGenerate = """
                                                                        using Test.Requests;
                                                                        using ValiCraft;
                                                                        using ValiCraft.Attributes;
                                                                        using ValiCraft.BuilderTypes;
                                                                        using ErrorCraft;

                                                                        namespace Test.Validators;

                                                                        [GenerateValidator]
                                                                        public partial class RequestValidator : Validator<Request>
                                                                        {
                                                                            protected override void DefineRules(IValidationRuleBuilder<Request> builder)
                                                                            {
                                                                                builder.EnsureEach(p => p.Tags)
                                                                                    .Is(t => !string.IsNullOrEmpty(t));
                                                                            }
                                                                        }
                                                                        """;

    [StringSyntax("CSharp")] private const string ExpectedValidators = """
                                                                       // <auto-generated />
                                                                       #nullable enable

                                                                       using Test.Requests;
                                                                       using ValiCraft;
                                                                       using ValiCraft.Attributes;
                                                                       using ValiCraft.BuilderTypes;
                                                                       using ErrorCraft;

                                                                       namespace Test.Validators
                                                                       {
                                                                           /// <summary>
                                                                           /// Generated validator for <see cref="global::Test.Requests.Request"/>.
                                                                           /// </summary>
                                                                           public partial class RequestValidator : global::ValiCraft.IValidator<global::Test.Requests.Request>
                                                                           {
                                                                               /// <inheritdoc />
                                                                               public global::ErrorCraft.ValidationErrors? Validate(global::Test.Requests.Request request)
                                                                               {
                                                                                   var errors = RunValidationLogic(request, null);

                                                                                   if (errors is null) return null;

                                                                                   return new global::ErrorCraft.ValidationErrors
                                                                                   {
                                                                                       Code = "RequestErrors",
                                                                                       Message = "One or more validation errors occurred.",
                                                                                       Severity = global::ErrorCraft.ErrorSeverity.Error,
                                                                                       Errors = errors
                                                                                   };
                                                                               }

                                                                               /// <inheritdoc />
                                                                               [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                                                                               public global::ErrorCraft.ValidationErrors? Validate(global::Test.Requests.Request request, string? inheritedTargetPath)
                                                                               {
                                                                                   var errors = RunValidationLogic(request, inheritedTargetPath);

                                                                                   if (errors is null) return null;

                                                                                   return new global::ErrorCraft.ValidationErrors
                                                                                   {
                                                                                       Code = "RequestErrors",
                                                                                       Message = "One or more validation errors occurred.",
                                                                                       Severity = global::ErrorCraft.ErrorSeverity.Error,
                                                                                       Errors = errors
                                                                                   };
                                                                               }

                                                                               private global::System.Collections.Generic.List<global::ErrorCraft.IValidationError>? RunValidationLogic(global::Test.Requests.Request request, string? inheritedTargetPath)
                                                                               {
                                                                                   global::System.Collections.Generic.List<global::ErrorCraft.IValidationError>? errors = null;

                                                                                   var index1 = 0;
                                                                                   foreach (var element in request.Tags)
                                                                                   {
                                                                                       if (!(!string.IsNullOrEmpty(element)))
                                                                                       {
                                                                                           errors ??= new(1);
                                                                                           errors.Add(new global::ErrorCraft.ValidationError<string>
                                                                                           {
                                                                                               Code = "Is",
                                                                                               Message = $"'Tags' doesn't satisfy the condition",
                                                                                               Severity = global::ErrorCraft.ErrorSeverity.Error,
                                                                                               TargetName = "Tags",
                                                                                               TargetPath = $"{inheritedTargetPath}{(inheritedTargetPath is not null ? "Tags[{index1}]" : null)}",
                                                                                               AttemptedValue = element,
                                                                                           });
                                                                                       }
                                                                                       index1++;
                                                                                   }

                                                                                   return errors;
                                                                               }
                                                                           }
                                                                       }
                                                                       """;

    [Fact]
    public void ShouldGenerateValidator()
    {
        AssertGenerator(inputs: [InputRequests, InputValidatorsToGenerate],
            outputs: [ExpectedValidators],
            diagnostics: [],
            assertInitialCompilation: true);
    }
}
