using System.Diagnostics.CodeAnalysis;
using ValiCraft.Generator.Tests.Helpers;

namespace ValiCraft.Generator.Tests.GeneratorTests;

public class SingleEnsureEachRuleChain_DirectRule_WithMessageFormatSpecifiersTest : IncrementalGeneratorTestBase<ValiCraftGenerator>
{
    [StringSyntax("CSharp")] private const string InputRequests = """
                                                             using System.Collections.Generic;

                                                             namespace Test.Requests;

                                                             public class Request
                                                             {
                                                                 public required List<decimal> Amounts { get; set; }
                                                             }
                                                             """;

    [StringSyntax("CSharp")] private const string InputValidatorsToGenerate = """
                                                                        using Test.Requests;
                                                                        using ValiCraft;
                                                                        using ValiCraft.Attributes;
                                                                        using ValiCraft.BuilderTypes;
                                                                        using ErrorCraft;

                                                                        namespace Test.Validators;

                                                                        [GenerateValidator]
                                                                        public partial class RequestValidator : Validator<Request>
                                                                        {
                                                                            protected override void DefineRules(IValidationRuleBuilder<Request> builder)
                                                                            {
                                                                                builder.EnsureEach(p => p.Amounts)
                                                                                    .IsGreaterThan(0m)
                                                                                        .WithMessage("'{TargetName}' must be positive. Current value: {TargetValue:C}");
                                                                            }
                                                                        }
                                                                        """;

    [StringSyntax("CSharp")] private const string ExpectedValidators = """
                                                                       // <auto-generated />
                                                                       #nullable enable

                                                                       using Test.Requests;
                                                                       using ValiCraft;
                                                                       using ValiCraft.Attributes;
                                                                       using ValiCraft.BuilderTypes;
                                                                       using ErrorCraft;

                                                                       namespace Test.Validators
                                                                       {
                                                                           /// <summary>
                                                                           /// Generated validator for <see cref="global::Test.Requests.Request"/>.
                                                                           /// </summary>
                                                                           public partial class RequestValidator : global::ValiCraft.IValidator<global::Test.Requests.Request>
                                                                           {
                                                                               /// <inheritdoc />
                                                                               public global::MonadCraft.Result<global::ErrorCraft.IValidationErrors, global::Test.Requests.Request> Validate(global::Test.Requests.Request request)
                                                                               {
                                                                                   var errors = RunValidationLogic(request, null);

                                                                                   return errors is not null
                                                                                       ? global::MonadCraft.Result<global::ErrorCraft.IValidationErrors, global::Test.Requests.Request>.Failure(new global::ErrorCraft.ValidationErrors
                                                                                       {
                                                                                           Code = "RequestErrors",
                                                                                           Message = "One or more validation errors occurred.",
                                                                                           Severity = global::ErrorCraft.ErrorSeverity.Error,
                                                                                           Errors = errors
                                                                                       })
                                                                                       : global::MonadCraft.Result<global::ErrorCraft.IValidationErrors, global::Test.Requests.Request>.Success(request);
                                                                               }

                                                                               /// <inheritdoc />
                                                                               public global::System.Collections.Generic.IReadOnlyList<global::ErrorCraft.IValidationError> ValidateToList(global::Test.Requests.Request request)
                                                                               {
                                                                                   return RunValidationLogic(request, null) ?? [];
                                                                               }

                                                                               /// <inheritdoc />
                                                                               [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                                                                               public global::System.Collections.Generic.IReadOnlyList<global::ErrorCraft.IValidationError> ValidateToList(global::Test.Requests.Request request, string? inheritedTargetPath)
                                                                               {
                                                                                   return RunValidationLogic(request, inheritedTargetPath) ?? [];
                                                                               }

                                                                               private global::System.Collections.Generic.List<global::ErrorCraft.IValidationError>? RunValidationLogic(global::Test.Requests.Request request, string? inheritedTargetPath)
                                                                               {
                                                                                   global::System.Collections.Generic.List<global::ErrorCraft.IValidationError>? errors = null;

                                                                                   var index1 = 0;
                                                                                   foreach (var element in request.Amounts)
                                                                                   {
                                                                                       if (!global::ValiCraft.Rules.GreaterThan(element, 0m))
                                                                                       {
                                                                                           errors ??= new(1);
                                                                                           errors.Add(new global::ErrorCraft.ValidationError<decimal>
                                                                                           {
                                                                                               Code = nameof(global::ValiCraft.Rules.GreaterThan),
                                                                                               Message = $"'Amounts' must be positive. Current value: {element:C}",
                                                                                               Severity = global::ErrorCraft.ErrorSeverity.Error,
                                                                                               TargetName = "Amounts",
                                                                                               TargetPath = $"{inheritedTargetPath}{(inheritedTargetPath is not null ? "Amounts[{index1}]" : null)}",
                                                                                               AttemptedValue = element,
                                                                                           });
                                                                                       }
                                                                                       index1++;
                                                                                   }

                                                                                   return errors;
                                                                               }
                                                                           }
                                                                       }
                                                                       """;

    [Fact]
    public void ShouldGenerateValidator()
    {
        AssertGenerator(inputs: [InputRequests, InputValidatorsToGenerate],
            outputs: [ExpectedValidators],
            diagnostics: [],
            assertInitialCompilation: true);
    }
}
