using System.Diagnostics.CodeAnalysis;
using ValiCraft.Generator.Tests.Helpers;

namespace ValiCraft.Generator.Tests.GeneratorTests;

public class SingleEnsureRuleChain_MethodTarget_MultipleRulesTest : IncrementalGeneratorTestBase<ValiCraftGenerator>
{
    [StringSyntax("CSharp")] private const string InputRequests = """
                                                             using System;

                                                             namespace Test.Requests;

                                                             public class User
                                                             {
                                                                 public string? FirstName { get; set; }
                                                                 public string? LastName { get; set; }
                                                                 public string GetDisplayName() => $"{FirstName} {LastName}";
                                                             }
                                                             """;

    // Define the validator against our request types.
    // This will generate a Validate method in a partial class.
    [StringSyntax("CSharp")] private const string InputValidatorsToGenerate = """
                                                                         using Test.Requests;
                                                                         using ValiCraft;
                                                                         using ValiCraft.Attributes;
                                                                         using ValiCraft.BuilderTypes;
                                                                         using ErrorCraft;

                                                                         namespace Test.Validators;

                                                                         [GenerateValidator]
                                                                         public partial class UserValidator : Validator<User>
                                                                         {
                                                                             protected override void DefineRules(IValidationRuleBuilder<User> userBuilder)
                                                                             {
                                                                                 userBuilder.Ensure(x => x.GetDisplayName())
                                                                                     .IsNotNullOrWhiteSpace()
                                                                                     .HasMinLength(2);
                                                                             }
                                                                         }
                                                                         """;

    [StringSyntax("CSharp")] private const string ExpectedValidators = """
                                                                       // <auto-generated />
                                                                       #nullable enable

                                                                       using Test.Requests;
                                                                       using ValiCraft;
                                                                       using ValiCraft.Attributes;
                                                                       using ValiCraft.BuilderTypes;
                                                                       using ErrorCraft;

                                                                       namespace Test.Validators
                                                                       {
                                                                           /// <summary>
                                                                           /// Generated validator for <see cref="global::Test.Requests.User"/>.
                                                                           /// </summary>
                                                                           public partial class UserValidator : global::ValiCraft.IValidator<global::Test.Requests.User>
                                                                           {
                                                                               /// <inheritdoc />
                                                                               public global::ErrorCraft.ValidationErrors? Validate(global::Test.Requests.User request)
                                                                               {
                                                                                   var errors = RunValidation(request, null);

                                                                                   if (errors is null) return null;

                                                                                   return new global::ErrorCraft.ValidationErrors
                                                                                   {
                                                                                       Code = "UserErrors",
                                                                                       Message = "One or more validation errors occurred.",
                                                                                       Severity = global::ErrorCraft.ErrorSeverity.Error,
                                                                                       Errors = errors
                                                                                   };
                                                                               }

                                                                               /// <inheritdoc />
                                                                               [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                                                                               public global::ErrorCraft.ValidationErrors? Validate(global::Test.Requests.User request, string? inheritedTargetPath)
                                                                               {
                                                                                   var errors = RunValidation(request, inheritedTargetPath);

                                                                                   if (errors is null) return null;

                                                                                   return new global::ErrorCraft.ValidationErrors
                                                                                   {
                                                                                       Code = "UserErrors",
                                                                                       Message = "One or more validation errors occurred.",
                                                                                       Severity = global::ErrorCraft.ErrorSeverity.Error,
                                                                                       Errors = errors
                                                                                   };
                                                                               }

                                                                               /// <summary>
                                                                               /// Runs the validation logic and returns the raw error list. This method is intended for internal use by nested validators.
                                                                               /// </summary>
                                                                               [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                                                                               public global::System.Collections.Generic.List<global::ErrorCraft.IValidationError>? RunValidation(global::Test.Requests.User request, string? inheritedTargetPath)
                                                                               {
                                                                                   global::System.Collections.Generic.List<global::ErrorCraft.IValidationError>? errors = null;

                                                                                   if (!global::ValiCraft.Rules.NotNullOrWhiteSpace(request.GetDisplayName()))
                                                                                   {
                                                                                       errors ??= new(2);
                                                                                       errors.Add(new global::ErrorCraft.ValidationError<string>
                                                                                       {
                                                                                           Code = nameof(global::ValiCraft.Rules.NotNullOrWhiteSpace),
                                                                                           Message = $"Get Display Name must not be null or contain only whitespace.",
                                                                                           Severity = global::ErrorCraft.ErrorSeverity.Error,
                                                                                           TargetName = "Get Display Name",
                                                                                           TargetPath = $"{inheritedTargetPath}GetDisplayName",
                                                                                           AttemptedValue = request.GetDisplayName(),
                                                                                       });
                                                                                   }
                                                                                   if (!global::ValiCraft.Rules.MinLength(request.GetDisplayName(), 2))
                                                                                   {
                                                                                       errors ??= new(1);
                                                                                       errors.Add(new global::ErrorCraft.ValidationError<string>
                                                                                       {
                                                                                           Code = nameof(global::ValiCraft.Rules.MinLength),
                                                                                           Message = $"Get Display Name must have a minimum length of 2",
                                                                                           Severity = global::ErrorCraft.ErrorSeverity.Error,
                                                                                           TargetName = "Get Display Name",
                                                                                           TargetPath = $"{inheritedTargetPath}GetDisplayName",
                                                                                           AttemptedValue = request.GetDisplayName(),
                                                                                       });
                                                                                   }

                                                                                   return errors;
                                                                               }
                                                                           }
                                                                       }
                                                                       """;

    [Fact]
    public void ShouldGenerateValidator()
    {
        AssertGenerator(inputs: [InputRequests, InputValidatorsToGenerate],
            outputs: [ExpectedValidators],
            diagnostics: [],
            assertInitialCompilation: true);
    }
}
