using System.Diagnostics.CodeAnalysis;
using ValiCraft.Generator.Tests.Helpers;

namespace ValiCraft.Generator.Tests.GeneratorTests;

public class SingleEnsureRuleChain_MethodTarget_WithOverridesTest : IncrementalGeneratorTestBase<ValiCraftGenerator>
{
    [StringSyntax("CSharp")] private const string InputRequests = """
                                                             using System;

                                                             namespace Test.Requests;

                                                             public class Account
                                                             {
                                                                 public decimal Balance { get; set; }
                                                                 public decimal GetAvailableBalance() => Balance;
                                                             }
                                                             """;

    // Define the validator against our request types.
    // This will generate a Validate method in a partial class.
    [StringSyntax("CSharp")] private const string InputValidatorsToGenerate = """
                                                                         using Test.Requests;
                                                                         using ValiCraft;
                                                                         using ValiCraft.Attributes;
                                                                         using ValiCraft.BuilderTypes;
                                                                         using ErrorCraft;

                                                                         namespace Test.Validators;

                                                                         [GenerateValidator]
                                                                         public partial class AccountValidator : Validator<Account>
                                                                         {
                                                                             protected override void DefineRules(IValidationRuleBuilder<Account> accountBuilder)
                                                                             {
                                                                                 accountBuilder.Ensure(x => x.GetAvailableBalance())
                                                                                     .IsGreaterThan(0)
                                                                                         .WithMessage("Insufficient funds")
                                                                                         .WithErrorCode("INSUFFICIENT_FUNDS");
                                                                             }
                                                                         }
                                                                         """;

    [StringSyntax("CSharp")] private const string ExpectedValidators = """
                                                                       // <auto-generated />
                                                                       #nullable enable

                                                                       using Test.Requests;
                                                                       using ValiCraft;
                                                                       using ValiCraft.Attributes;
                                                                       using ValiCraft.BuilderTypes;
                                                                       using ErrorCraft;

                                                                       namespace Test.Validators
                                                                       {
                                                                           /// <summary>
                                                                           /// Generated validator for <see cref="global::Test.Requests.Account"/>.
                                                                           /// </summary>
                                                                           public partial class AccountValidator : global::ValiCraft.IValidator<global::Test.Requests.Account>
                                                                           {
                                                                               /// <inheritdoc />
                                                                               public global::ErrorCraft.ValidationErrors? Validate(global::Test.Requests.Account request)
                                                                               {
                                                                                   var errors = RunValidation(request, null);

                                                                                   if (errors is null) return null;

                                                                                   return new global::ErrorCraft.ValidationErrors
                                                                                   {
                                                                                       Code = "AccountErrors",
                                                                                       Message = "One or more validation errors occurred.",
                                                                                       Severity = global::ErrorCraft.ErrorSeverity.Error,
                                                                                       Errors = errors
                                                                                   };
                                                                               }

                                                                               /// <inheritdoc />
                                                                               [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                                                                               public global::ErrorCraft.ValidationErrors? Validate(global::Test.Requests.Account request, string? inheritedTargetPath)
                                                                               {
                                                                                   var errors = RunValidation(request, inheritedTargetPath);

                                                                                   if (errors is null) return null;

                                                                                   return new global::ErrorCraft.ValidationErrors
                                                                                   {
                                                                                       Code = "AccountErrors",
                                                                                       Message = "One or more validation errors occurred.",
                                                                                       Severity = global::ErrorCraft.ErrorSeverity.Error,
                                                                                       Errors = errors
                                                                                   };
                                                                               }

                                                                               /// <summary>
                                                                               /// Runs the validation logic and returns the raw error list. This method is intended for internal use by nested validators.
                                                                               /// </summary>
                                                                               [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                                                                               public global::System.Collections.Generic.List<global::ErrorCraft.IValidationError>? RunValidation(global::Test.Requests.Account request, string? inheritedTargetPath)
                                                                               {
                                                                                   global::System.Collections.Generic.List<global::ErrorCraft.IValidationError>? errors = null;

                                                                                   if (!global::ValiCraft.Rules.GreaterThan(request.GetAvailableBalance(), 0))
                                                                                   {
                                                                                       errors ??= new(1);
                                                                                       errors.Add(new global::ErrorCraft.ValidationError<decimal>
                                                                                       {
                                                                                           Code = "INSUFFICIENT_FUNDS",
                                                                                           Message = $"Insufficient funds",
                                                                                           Severity = global::ErrorCraft.ErrorSeverity.Error,
                                                                                           TargetName = "Get Available Balance",
                                                                                           TargetPath = $"{inheritedTargetPath}GetAvailableBalance",
                                                                                           AttemptedValue = request.GetAvailableBalance(),
                                                                                       });
                                                                                   }

                                                                                   return errors;
                                                                               }
                                                                           }
                                                                       }
                                                                       """;

    [Fact]
    public void ShouldGenerateValidator()
    {
        AssertGenerator(inputs: [InputRequests, InputValidatorsToGenerate],
            outputs: [ExpectedValidators],
            diagnostics: [],
            assertInitialCompilation: true);
    }
}
