using Microsoft.Extensions.DependencyInjection;

namespace ValiCraft.DependencyInjection;

/// <summary>
/// Defines a module that can register ValiCraft validators with a service collection.
/// Implementations are generated by the ValiCraft source generator for each project containing validators.
/// </summary>
public interface IValiCraftModule
{
    /// <summary>
    /// Registers the validators defined in this module with the specified service collection.
    /// </summary>
    /// <param name="services">The service collection to register validators with.</param>
    /// <param name="lifetime">The service lifetime for the registered validators.</param>
    static abstract void Register(IServiceCollection services, ServiceLifetime lifetime);
}
